<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PriceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('prices')->delete();

        DB::table('prices')->insert(array (
            0 => array (
                'id' => 1,
                'product_id' => 1,
                'discount' => 300,
                'company_price' => 12536,
                'warehouse_price' => 12686,
                'ht_warehouse_price' => 12716,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            1 => array (
                'id' => 2,
                'product_id' => 2,
                'discount' => 300,
                'company_price' => 12536,
                'warehouse_price' => 12686,
                'ht_warehouse_price' => 12716,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            2 => array (
                'id' => 3,
                'product_id' => 3,
                'discount' => 300,
                'company_price' => 11919,
                'warehouse_price' => 12069,
                'ht_warehouse_price' => 12099,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            3 => array (
                'id' => 4,
                'product_id' => 4,
                'discount' => 300,
                'company_price' => 11919,
                'warehouse_price' => 12069,
                'ht_warehouse_price' => 12099,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            4 => array (
                'id' => 5,
                'product_id' => 5,
                'discount' => 300,
                'company_price' => 11749,
                'warehouse_price' => 11899,
                'ht_warehouse_price' => 11929,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            5 => array (
                'id' => 6,
                'product_id' => 6,
                'discount' => 300,
                'company_price' => 11749,
                'warehouse_price' => 11899,
                'ht_warehouse_price' => 11929,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            6 => array (
                'id' => 7,
                'product_id' => 7,
                'discount' => 500,
                'company_price' => 10823,
                'warehouse_price' => 10973,
                'ht_warehouse_price' => 11003,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            7 => array (
                'id' => 8,
                'product_id' => 8,
                'discount' => 500,
                'company_price' => 19336,
                'warehouse_price' => 19486,
                'ht_warehouse_price' => 19516,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            8 => array (
                'id' => 9,
                'product_id' => 9,
                'discount' => 500,
                'company_price' => 18883,
                'warehouse_price' => 19033,
                'ht_warehouse_price' => 19063,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            9 => array (
                'id' => 10,
                'product_id' => 10,
                'discount' => 500,
                'company_price' => 18541,
                'warehouse_price' => 18691,
                'ht_warehouse_price' => 18721,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            10 => array (
                'id' => 11,
                'product_id' => 11,
                'discount' => 500,
                'company_price' => 24618,
                'warehouse_price' => 24768,
                'ht_warehouse_price' => 24798,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            11 => array (
                'id' => 12,
                'product_id' => 12,
                'discount' => 500,
                'company_price' => 23997,
                'warehouse_price' => 24147,
                'ht_warehouse_price' => 24177,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            12 => array (
                'id' => 13,
                'product_id' => 13,
                'discount' => 500,
                'company_price' => 18061,
                'warehouse_price' => 18211,
                'ht_warehouse_price' => 18241,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            13 => array (
                'id' => 14,
                'product_id' => 14,
                'discount' => 300,
                'company_price' => 13020,
                'warehouse_price' => 13200,
                'ht_warehouse_price' => 13170,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            14 => array (
                'id' => 15,
                'product_id' => 15,
                'discount' => 300,
                'company_price' => 12413,
                'warehouse_price' => 12563,
                'ht_warehouse_price' => 12593,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            15 => array (
                'id' => 16,
                'product_id' => 16,
                'discount' => 300,
                'company_price' => 12145,
                'warehouse_price' => 12295,
                'ht_warehouse_price' => 12325,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            16 => array (
                'id' => 17,
                'product_id' => 17,
                'discount' => 300,
                'company_price' => 11992,
                'warehouse_price' => 12142,
                'ht_warehouse_price' => 12172,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            17 => array (
                'id' => 18,
                'product_id' => 18,
                'discount' => 500,
                'company_price' => 11231,
                'warehouse_price' => 11381,
                'ht_warehouse_price' => 11411,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            18 => array (
                'id' => 19,
                'product_id' => 19,
                'discount' => 500,
                'company_price' => 13312,
                'warehouse_price' => 13462,
                'ht_warehouse_price' => 13492,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            19 => array (
                'id' => 20,
                'product_id' => 20,
                'discount' => 300,
                'company_price' => 12079,
                'warehouse_price' => 12229,
                'ht_warehouse_price' => 12259,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            20 => array (
                'id' => 21,
                'product_id' => 21,
                'discount' => 300,
                'company_price' => 11815,
                'warehouse_price' => 11965,
                'ht_warehouse_price' => 11995,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ));
    }
}
